development:
  adapter: postgresql
  encoding: utf8
  database: characturge_online_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: characturge_online_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: characturge_online
  pool: 5
  username:
  password:
