development:
  adapter: postgresql
  encoding: utf8
  database: characturge_online_development
  pool: 5
  username: vagrant
  password: ''
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: characturge_online_test
  pool: 5
  username: vagrant
  password: ''
  host: localhost
